### ISSUE TITLE
automatic code style format checking

### ISSUE THREAD

**Issue by aradermacher** [BAMresearch/PGDrome#13]
integrate automatic code formatting in git workflow

similar to https://github.com/BAMresearch/probeye/blob/main/.github/workflows/push.yaml

**Comment by DoStrobl** [comment]
In addition to the change of the workflow a pre-commit-config.yaml is needed similar to [https://github.com/BAMresearch/probeye/blob/main/.pre-commit-config.yaml](https://github.com/BAMresearch/probeye/blob/main/.pre-commit-config.yaml)
